language: node_js
node_js:
    - '0.10'
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g bower karma grunt-cli jshint'
    - 'npm install'
    - 'cd node_modules/spies'
    - 'npm install'
    - 'cd -'
    - 'ls -alF node_modules/spies/node_modules'
    - 'ls -alF node_modules/spies/node_modules/chai'
    - 'ls -alF node_modules/spies/node_modules/traceur'
script:
    - 'gulp check'